#!/usr/bin/env python3
"""Render the tested-version table in COMPATIBILITY.md from install.sh.

Single source of truth: the ``COMPAT-`` block near the top of ``install.sh``.
This script only rewrites the region between the ``COMPAT:START`` and
``COMPAT:END`` markers, so the rest of COMPATIBILITY.md stays hand-written.

Usage:
    python3 scripts/gen_compat.py                 # rewrite the generated block
    python3 scripts/gen_compat.py --check         # exit 1 if the doc has drifted
    python3 scripts/gen_compat.py --adopt <host>  # record a device's versions

``--adopt <ssh-host>`` reads the tool versions installed on that device (via the
same PATH layout and version extraction the toolkit itself uses) and raises the
``TESTED_*`` constants in install.sh to match. It never downgrades a recorded
value, so adopting from an older device cannot erase a newer verification.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INSTALL_SH = ROOT / "install.sh"
COMPAT_MD = ROOT / "COMPATIBILITY.md"

START = "<!-- COMPAT:START"
END = "<!-- COMPAT:END -->"

# tool key -> display label, in table order
TOOLS = [
    ("openclaw", "OpenClaw"),
    ("hermes", "Hermes"),
    ("nanobot", "Nanobot"),
    ("gemini", "Gemini CLI"),
    ("pi", "Pi Coding Agent"),
    ("ollama", "Ollama"),
    ("n8n", "n8n"),
    ("paperclip", "Paperclip"),
]

NOT_RECORDED = "- (not yet recorded)"

# Mirrors install.sh's compat_installed(): PATH includes the pnpm and local bin
# dirs (a non-interactive ssh shell does not source .bashrc), grep the whole
# banner for a semver rather than taking the first line, because some CLIs print
# a warning line before the version.
REMOTE_PROBE = r"""
export PATH="$HOME/.local/share/pnpm:$HOME/.local/bin:$PREFIX/bin:$PATH"
echo "env=$(uname -m), Android $(getprop ro.build.version.release) (API $(getprop ro.build.version.sdk)), $(awk '/^MemTotal/{printf "%.1f", $2/1048576}' /proc/meminfo) GB RAM"
for t in openclaw hermes gemini pi ollama n8n nanobot; do
    if command -v "$t" >/dev/null 2>&1; then
        v=$("$t" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        [ -n "$v" ] && printf 'tool=%s=%s\n' "$t" "$v"
    fi
done
"""


def read_install_sh() -> tuple[dict[str, str], dict[str, str]]:
    """Return (meta, tested) parsed from install.sh."""
    text = INSTALL_SH.read_text(encoding="utf-8")

    def grab(name: str) -> str:
        match = re.search(rf'^{name}="([^"]*)"', text, re.MULTILINE)
        if not match:
            sys.exit(f"gen_compat: {name} not found in install.sh")
        return match.group(1)

    meta = {
        "COMPAT_UPDATED": grab("COMPAT_UPDATED"),
        "TESTED_ENVS": grab("TESTED_ENVS"),
    }
    tested = dict(re.findall(r'^(TESTED_[A-Z0-9_]+)="([^"]*)"', text, re.MULTILINE))
    tested.pop("TESTED_ENVS", None)
    return meta, tested


def render_block(meta: dict[str, str], tested: dict[str, str]) -> str:
    environments = [p.strip() for p in meta["TESTED_ENVS"].split("|") if p.strip()]
    lines = [
        f"{START} (generated by scripts/gen_compat.py from install.sh — do not edit by hand) -->",
        "",
        f"**Last updated:** {meta['COMPAT_UPDATED']}",
        "",
        "Verified environment classes (architecture, Android version, memory):",
        "",
    ]
    lines += [f"- `{env}`" for env in environments]
    lines += [
        "",
        "| Tool | Tested against |",
        "| :--- | :--- |",
    ]
    for key, label in TOOLS:
        value = tested.get(f"TESTED_{key.upper()}", "unknown")
        shown = f"`{value}`" if value and value != "unknown" else NOT_RECORDED
        lines.append(f"| {label} | {shown} |")
    lines += ["", END]
    return "\n".join(lines)


def version_key(value: str) -> tuple[int, ...]:
    return tuple(int(part) for part in re.findall(r"\d+", value))


def adopt(host: str) -> int:
    """Raise TESTED_* constants in install.sh to match the given device."""
    try:
        result = subprocess.run(
            ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", host, REMOTE_PROBE],
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        sys.exit(f"gen_compat: could not reach {host}: {exc}")

    if result.returncode != 0:
        sys.exit(f"gen_compat: ssh {host} failed:\n{result.stderr.strip()}")

    device_env = ""
    reported: dict[str, str] = {}
    for line in result.stdout.splitlines():
        if line.startswith("env="):
            device_env = line[4:]
        elif line.startswith("tool="):
            _, name, version = line.split("=", 2)
            reported[name] = version

    _meta, current = read_install_sh()
    text = INSTALL_SH.read_text(encoding="utf-8")
    changes: list[str] = []
    seen: list[str] = []

    for key in sorted(reported):
        const = f"TESTED_{key.upper()}"
        if f"{const}=" not in text:
            continue
        old = current.get(const, "unknown")
        new = reported[key]
        if old != "unknown" and version_key(old) >= version_key(new):
            seen.append(f"  {key:<9} {new} (from {host}) — kept recorded {old} (not older)")
            continue
        text = re.sub(rf'^{const}="[^"]*"', f'{const}="{new}"', text, count=1, flags=re.MULTILINE)
        changes.append(f"  {key:<9} {old} -> {new}")
        seen.append(f"  {key:<9} {new} (from {host}) — recorded")

    if device_env:
        print(f"device {host}: {device_env}")
    for line in seen:
        print(line)

    if not changes:
        print("gen_compat: nothing to raise")
        return 0

    INSTALL_SH.write_text(text, encoding="utf-8")
    print("\ngen_compat: install.sh updated:")
    for line in changes:
        print(line)

    if device_env:
        print(
            "\ngen_compat: TESTED_ENVS is manual — add/adjust this device's class if new:\n"
            f'  "{device_env}"'
        )

    meta, tested = read_install_sh()
    doc = COMPAT_MD.read_text(encoding="utf-8")
    start = doc.index(START)
    end = doc.index(END) + len(END)
    COMPAT_MD.write_text(doc[:start] + render_block(meta, tested) + doc[end:], encoding="utf-8")
    print("gen_compat: COMPATIBILITY.md regenerated")
    return 0


def main() -> int:
    args = sys.argv[1:]

    if "--adopt" in args:
        index = args.index("--adopt")
        if index + 1 >= len(args):
            sys.exit("gen_compat: --adopt needs an ssh host (e.g. --adopt 8x)")
        return adopt(args[index + 1])

    meta, tested = read_install_sh()
    block = render_block(meta, tested)

    doc = COMPAT_MD.read_text(encoding="utf-8")
    try:
        start = doc.index(START)
        end = doc.index(END) + len(END)
    except ValueError:
        sys.exit("gen_compat: COMPATIBILITY.md is missing the COMPAT:START/END markers")

    updated = doc[:start] + block + doc[end:]

    if "--check" not in args:
        COMPAT_MD.write_text(updated, encoding="utf-8")
        print("gen_compat: COMPATIBILITY.md updated")
        return 0

    if updated != doc:
        print(
            "gen_compat: COMPATIBILITY.md is stale — run: python3 scripts/gen_compat.py",
            file=sys.stderr,
        )
        return 1

    print("gen_compat: COMPATIBILITY.md is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
